/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Nasabah;
import Controller.Controller;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class TarikUangTeller extends javax.swing.JFrame {
     Controller controller = new Controller();
    private Nasabah nasabah;
    /**
     * Creates new form TransferATM
     */
    public TarikUangTeller(Nasabah nasabah) {
        initComponents();
        this.nasabah = nasabah;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNominalTarikTeller = new javax.swing.JTextField();
        btnOKTarikATM = new javax.swing.JButton();
        btnCancelTarikATM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setText("Tarik Uang Teller");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("Nominal :");

        btnOKTarikATM.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnOKTarikATM.setText("OK");
        btnOKTarikATM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKTarikATMActionPerformed(evt);
            }
        });

        btnCancelTarikATM.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnCancelTarikATM.setText("Cancel");
        btnCancelTarikATM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelTarikATMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tfNominalTarikTeller, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnOKTarikATM)
                        .addGap(36, 36, 36)
                        .addComponent(btnCancelTarikATM))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNominalTarikTeller, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelTarikATM)
                    .addComponent(btnOKTarikATM))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKTarikATMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKTarikATMActionPerformed
        try{
            Long saldo_awal = nasabah.getSaldo();
            Long saldo_kurang = Long.parseLong(tfNominalTarikTeller.getText());
            if(saldo_kurang < 1){
                throw new NumberFormatException("Error");
            }
            if(saldo_kurang > saldo_awal){
                throw new Exception("Error");
            }
            nasabah.setSaldo(saldo_awal-saldo_kurang);
           
            JOptionPane.showMessageDialog(null, "Transaksi berhasil!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Nominal salah!", "Error", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Saldo tidak cukup!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if(controller.tarikUangTeller(nasabah)){
            controller.MenuTeller(nasabah);
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_btnOKTarikATMActionPerformed

    private void btnCancelTarikATMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelTarikATMActionPerformed
        controller.MenuATM(nasabah);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelTarikATMActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TarikUangATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TarikUangATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TarikUangATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TarikUangATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TarikUangATM().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelTarikATM;
    private javax.swing.JButton btnOKTarikATM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfNominalTarikTeller;
    // End of variables declaration//GEN-END:variables
}
