/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;
import Dao.NasabahDao;
import Dao.TransaksiDao;
import Model.Nasabah;
import Model.Transaksi;
import Service.NasabahService;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class TransferATM extends javax.swing.JFrame {
Controller controller = new Controller();
NasabahDao dao = new NasabahDao();
TransaksiDao transaksiDao = new TransaksiDao();
private Nasabah nasabah;
private Transaksi transaksi;
    /**
     * Creates new form TransferView
     */
    public TransferATM() {
        initComponents();
        this.nasabah=nasabah;
    }

    public TransferATM(Nasabah nasabah) {
        initComponents();
        this.nasabah=nasabah;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNominalTfATM = new javax.swing.JTextField();
        bTransfer = new javax.swing.JButton();
        btnCancelTfATM = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfTransferNama = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Transfer ATM");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("Nominal");

        bTransfer.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        bTransfer.setText("OK");
        bTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTransferActionPerformed(evt);
            }
        });

        btnCancelTfATM.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnCancelTfATM.setText("CANCEL");
        btnCancelTfATM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelTfATMActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("Nama Tujuan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(bTransfer)
                .addGap(18, 18, 18)
                .addComponent(btnCancelTfATM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfNominalTfATM, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(tfTransferNama, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTransferNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNominalTfATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bTransfer)
                    .addComponent(btnCancelTfATM))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTransferActionPerformed
        String to = tfTransferNama.getText();
        boolean success = false;
        Long saldo_awal = nasabah.getSaldo();
        Long saldo_kurang = Long.parseLong(tfNominalTfATM.getText());
        try{
            if(saldo_kurang < 1){
                throw new NumberFormatException("Error");
            }
            if(saldo_kurang > saldo_awal){
                throw new Exception("Error");
            }
            success = true;
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Nominal salah!", "Error", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Saldo tidak cukup!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if(success){
            success = false;
            ArrayList<Nasabah> list = dao.findAll();
            for(Nasabah u : list){
                if (to.equals(u.getNama())) {
                    Transaksi t = new Transaksi(nasabah, u, "Transfer", saldo_kurang);
                    transaksiDao.save(t);
                    JOptionPane.showMessageDialog(null, "Transaksi sukses!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    u.setSaldo(u.getSaldo()+saldo_kurang);
                    nasabah.setSaldo(saldo_awal-saldo_kurang);
                    success = true;
                    break;
                }
            }
            if(!success) {
                JOptionPane.showMessageDialog(null, "Transaksi gagal, tujuan "+to+" tidak terdaftar!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        if(controller.transferATM(nasabah)){
            controller.MenuATM(nasabah);
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_bTransferActionPerformed

    private void btnCancelTfATMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelTfATMActionPerformed
        controller.MenuATM(nasabah);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelTfATMActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TransferView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TransferView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TransferView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TransferView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TransferView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bTransfer;
    private javax.swing.JButton btnCancelTfATM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfNominalTfATM;
    private javax.swing.JTextField tfTransferNama;
    // End of variables declaration//GEN-END:variables
}
