/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekbankdhila.view;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import projekbankdhila.login.Login;
import projekbankdhila.login.LoginATM;
import projekbankdhila.login.LoginTeller;
import projekbankdhila.model.Nasabah;

/**
 *
 * @author ASUS
 */
public class LoginLayar extends javax.swing.JFrame {


    //Nasabah nasabah;
    /**
     * Creates new form LoginLayar
     */
    public LoginLayar() {
        initComponents();
        //this.nasabah = nasabah;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        isinopin = new javax.swing.JTextField();
        btnATM = new javax.swing.JButton();
        btnTeller = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        isiRek = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        setForeground(new java.awt.Color(255, 51, 255));

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dubai Light", 1, 24)); // NOI18N
        jLabel1.setText("No.Rek : ");

        jLabel2.setFont(new java.awt.Font("Dubai Light", 1, 24)); // NOI18N
        jLabel2.setText("PIN :");

        isinopin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        isinopin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isinopinActionPerformed(evt);
            }
        });

        btnATM.setBackground(new java.awt.Color(255, 255, 0));
        btnATM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnATM.setText("LOGIN ATM");
        btnATM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnATMActionPerformed(evt);
            }
        });

        btnTeller.setBackground(new java.awt.Color(255, 255, 0));
        btnTeller.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTeller.setText("LOGIN Teller");
        btnTeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTellerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel3.setText("Bank Office ");

        jLabel4.setText("Silahkan isi data dibawah");

        isiRek.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        isiRek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiRekActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 102));
        jLabel5.setText("Barokah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 62, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isiRek, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isinopin, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnATM)
                                .addGap(28, 28, 28)
                                .addComponent(btnTeller))
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isiRek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isinopin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(102, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnATM)
                            .addComponent(btnTeller))
                        .addGap(47, 47, 47))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isinopinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isinopinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isinopinActionPerformed

    private void btnATMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnATMActionPerformed
         LoginATM login = new LoginATM();
        int noRek = Integer.parseInt(isiRek.getText().toString());
         int pin = Integer.parseInt(isinopin.getText().toString());
         Nasabah nasabah = new Nasabah(noRek, pin);
         Nasabah nasabahLogin = login.loginATM(nasabah);
         
         System.out.println(nasabah.getNama());
         System.out.println(nasabah.getPin());
         
         if(nasabahLogin ==null){
            JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "No Rekening / PIN anda Salah!!", "Login Failed",JOptionPane.ERROR_MESSAGE);
        }else{
            JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "Silahkan pilih Layanan ATM yang diinginkan", "Login Success",JOptionPane.INFORMATION_MESSAGE);
            ATMLayanan atmLayanan = new ATMLayanan(nasabahLogin);
            atmLayanan.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnATMActionPerformed

    private void btnTellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTellerActionPerformed
         LoginTeller login = new LoginTeller();
        int noRek = Integer.parseInt(isiRek.getText().toString());
         int pin = Integer.parseInt(isinopin.getText().toString());
         Nasabah nasabah = new Nasabah(noRek, pin);
         Nasabah nasabahLogin = login.loginTeller(nasabah);
         
         if(nasabahLogin ==null){
            JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "No Rekening / PIN anda Salah!!", "Login Failed",JOptionPane.ERROR_MESSAGE);
        }else{
            JPanel panel = new JPanel();
            JOptionPane.showMessageDialog(panel, "Silahkan pilih Layanan Teller yang diinginkan", "Login Success",JOptionPane.INFORMATION_MESSAGE);
            TellerLayanan tellerLayanan = new TellerLayanan(nasabahLogin);
            tellerLayanan.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnTellerActionPerformed

    private void isiRekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiRekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiRekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginLayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginLayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginLayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginLayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new LoginLayar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnATM;
    private javax.swing.JButton btnTeller;
    private javax.swing.JTextField isiRek;
    private javax.swing.JTextField isinopin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
